app:
  name: meilisearch
  image:
    repository: getmeili/meilisearch
    pullPolicy: IfNotPresent
    tag: v1.54.0@sha256:0bf32debcbfa8ba4e418679025f4935884972171513c92f0584689ff994a61df

  service:
    port: 7700
    targetPort: 7700

  volumeMounts:
    - mountPath: /meili_data
      subPath: meili_data

  envFromSecrets:
    enabled: true
    secretRefNames:
      - meilisearch
