app:
  name: meilisearch
  image:
    repository: getmeili/meilisearch
    pullPolicy: IfNotPresent
    tag: v1.54.1@sha256:6f6c72d43008f227a7329422aa723ab5b4929e1fad8e68743062b050c36fb7ad

  service:
    port: 7700
    targetPort: 7700

  volumeMounts:
    - mountPath: /meili_data
      subPath: meili_data

  envFromSecrets:
    enabled: true
    secretRefNames:
      - meilisearch
