# renovate: depName=linuxserver/speedtest-tracker datasource=docker
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest
spec:
  values:
    app:
      replicaCount: 1
    ingress:
      enabled: true
      host: speedtest.shakir.cloud
      ingressClassName: traefik

    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      storageClassName: nfs-client
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main
