apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: namespaces
    - name: helm-repos
  path: ./flux/clusters/prod/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
