# native Kustomize entrypoint for the prod cluster.
# It lists every Flux Kustomization CRD that Flux should reconcile.
# Flux watches this directory and applies whatever is listed here.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - helm-repos.yaml
  - csi-driver-nfs.yaml
  - metallb.yaml
  - metallb-config.yaml
  - bw-secrets.yaml
  - apps.yaml
