apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: flux-system
  path: ./flux/clusters/prod/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
