apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notifications
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: notifications
spec:
  # Reconciles notifications, uses Flux's native notification CRDs
  interval: 10m
  path: ./clusters/prod/notifications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: bw-secrets
