app:
  name: netalertx
  image:
    repository: jokobsk/netalertx
    pullPolicy: IfNotPresent
    tag: 26@sha256:cd5176052fec71a75c902cc555e97cb540833d79c7cac8695c6adc611c402347

  service:
    port: 80
    targetPort: 20211

  volumeMounts:
    - mountPath: /data
      subPath: data

  env:
    - name: TZ
      value: "America/Los_Angeles"
    - name: PORT
      values: 20211
    - name: NETALERTX_UID
      value: 20211
    - name: NETALERTX_GID
      value: 20211
    - name: ALWAYS_FRESH_INSTALL
      value: "false"
