app:
  name: linkwarden
  image:
    repository: ghcr.io/linkwarden/linkwarden
    pullPolicy: IfNotPresent
    tag: latest@sha256:0664c28a039bda8ffa6663389e8536b2fc717219e329f85b83faca7efed3b144

  service:
    port: 80
    targetPort: 3000

  volumeMounts:
    - mountPath: /data/data
      subPath: data

  dbHostname: postgres-unichart

  envFromSecrets:
    enabled: true
    secretRefNames:
      - meilisearch
      - linkwarden
  env:
    - name: NEXTAUTH_URL
      value: "http://localhost:3000/api/v1/auth	"
    - name: MEILI_HOST
      value: "meilisearch-unichart.apps.svc.cluster.local"

## ------------ StatefulSet Specifications ------------ ##
database:
  enabled: true
  host: postgres-unichart
  port: 5432
  image:
    repository: postgres
    tag: 16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea
  volumeMounts:
    - mountPath: /var/lib/postgresql/data
      subPath: pgdata
  securityContext:
    enabled: true
    runAsUser: 999
    runAsGroup: 999
#    runAsNonRoot: false
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
