resources:
  - release.yaml

configMapGenerator:
  - name: prometheus-values
    files:
      - values.yaml=prometheus-values.yaml

generatorOptions:
  disableNameSuffixHash: true

# pseduo code
# depends on:
#   - bootstrap/bw-tokens/monitoring.yaml
#   - helm-repos
