app:
  name: deemix
  image:
    repository: ghcr.io/bambanah/deemix
    pullPolicy: IfNotPresent
    tag: v4.6.0@sha256:5ac6df2b8b3267cfc9c7599c57d0be850ebb1fb66fb2d42e7258491ebf3318d4

  service:
    port: 80
    targetPort: 6595

  volumeMounts:
    - mountPath: /downloads
      subPath: downloads
    - mountPath: /config
      subPath: config

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: UMASK_SET
      value: "022"
    - name: DEEMIX_SINGLE_USER
      value: "true"


