app:
  name: excalidraw
  image:
    repository: excalidraw/excalidraw
    pullPolicy: IfNotPresent
    tag: latest@sha256:20ffa04668e19616bb0c1b3632849e5cd96e0bc7a1336b73d9d072667f2c2854 # renovate: depName=excalidraw/excalidraw

  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 80
