# renovate: depName=docker.io/actualbudget/actual-server datasource=docker
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
spec:
  values:
    app:
      image:
        digest: "sha256:0b6c761f15dda9b4fb4c2b66d87e94b8f9cc646c18045382bfc49c1d35b52a7e"
        tag: sha-23adf06
      replicaCount: 1
    ingress:
      enabled: true
      host: budget.shakir.cloud
      ingressClassName: traefik
    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/actualbudget
