
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
spec:
  values:
    app:
      image:
        tag: sha-23adf06 # renovate: depName=docker.io/actualbudget/actual-server datasource=docker
      replicaCount: 1
    ingress:
      enabled: true
      host: budget.shakir.cloud
      ingressClassName: traefik
    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/actualbudget
