app:
  name: actualbudget
  image:
    repository: docker.io/actualbudget/actual-server
    pullPolicy: IfNotPresent
    tag: latest@sha256:b733ae30c70a66dc4d03577526e53575a0c04eab4f3ab6ace30934776251058c # renovate: depName=docker.io/actualbudget/actual-server datasource=docker

  service:
    port: 80
    targetPort: 5006

  volumeMounts:
    - mountPath: /data
      subPath: data

  livenessProbe:
    enabled: true
    command: ["node", "src/scripts/health-check.js"]
    initialDelaySeconds: 20
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 3
