app:
  name: actualbudget
  image:
    repository: docker.io/actualbudget/actual-server
    pullPolicy: IfNotPresent
    tag: latest@sha256:b0e732e2c41b3dc468a71548e88ef76d3f0c157fc43d15fa05d14ec1c5747e1e # renovate: depName=docker.io/actualbudget/actual-server datasource=docker

  service:
    port: 80
    targetPort: 5006

  volumeMounts:
    - mountPath: /data
      subPath: data

  livenessProbe:
    enabled: true
    command: ["node", "src/scripts/health-check.js"]
    initialDelaySeconds: 20
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 3
