app:
  name: omnitools
  image:
    repository: iib0011/omni-tools
    pullPolicy: IfNotPresent
    tag: "0.6" # renovate: depName=iib0011/omni-tools

  containerPort: 80

  service:
    port: 80
    targetPort: 80
