apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  values:
    replicaCount: 1
    ingress:
      enabled: true
      className: "traefik"
      annotations: {}
      hosts:
        - host: jellyfin.shakir.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
