app:
  name: speedtest
  image:
    repository: linuxserver/speedtest-tracker
    pullPolicy: IfNotPresent
    tag: 1.13.12@sha256:eb3d249f16177964daa4fff7f6a90bbf6645f4e23158d92f5cddb133728d0804
  containerPort: 80

  service:
    port: 80
    targetPort: 80

  volumeMounts:
    - mountPath: /config
      subPath: config

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "America/Los_Angeles"
    - name: OOKLA_EULA_GDPR
      value: "true"
    - name: DB_CONNECTION
      value: sqlite
