app:
  name: speedtest
  image:
    repository: linuxserver/speedtest-tracker
    pullPolicy: IfNotPresent
    tag: 1.14.5@sha256:4c698dc3a5d989c8d92512600d303f23ff2e6e789c89674adb083372ac67fe2c
  containerPort: 80

  service:
    port: 80
    targetPort: 80

  volumeMounts:
    - mountPath: /config
      subPath: config

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "America/Los_Angeles"
    - name: OOKLA_EULA_GDPR
      value: "true"
    - name: DB_CONNECTION
      value: sqlite
