app:
  name: speedtest
  image:
    repository: linuxserver/speedtest-tracker
    pullPolicy: IfNotPresent
    tag: 1.14.2@sha256:3f75c5ec7a14c232f91af1ddda4248543bb2e8f0aeb18fec64c34d2f42dd00ce
  containerPort: 80

  service:
    port: 80
    targetPort: 80

  volumeMounts:
    - mountPath: /config
      subPath: config

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "America/Los_Angeles"
    - name: OOKLA_EULA_GDPR
      value: "true"
    - name: DB_CONNECTION
      value: sqlite
