app:
  name: metube
  image:
    repository: ghcr.io/alexta69/metube
    pullPolicy: IfNotPresent
    tag: "2026.06.20@sha256:a07754cef9632f59d947f5dc0833e8e085476e5e2e999966216453139257db3e" # renovate: depName=ghcr.io/alexta69/metube
  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 8081

  volumeMounts:
    - mountPath: /downloads
      subPath: downloads

