app:
  name: metube
  image:
    repository: ghcr.io/alexta69/metube
    pullPolicy: IfNotPresent
    tag: "2026.07.05@sha256:48c8700bccd51f828606464ad12147b76f5ce7ef1d9ed935bd933f5e8c816fe9" # renovate: depName=ghcr.io/alexta69/metube
  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 8081

  volumeMounts:
    - mountPath: /downloads
      subPath: downloads

