app:
  name: metube
  image:
    repository: ghcr.io/alexta69/metube
    pullPolicy: IfNotPresent
    tag: "2026.07.10@sha256:3ac9c2ccff659b3063dcd4ddfdae1e92fd5c64e88bb2f4a58b9855d655a7acd8" # renovate: depName=ghcr.io/alexta69/metube
  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 8081

  volumeMounts:
    - mountPath: /downloads
      subPath: downloads

