app:
  name: bentopdf
  image:
    repository: ghcr.io/alam00000/bentopdf
    pullPolicy: IfNotPresent
    tag: 2.8.2 # renovate: depName=ghcr.io/alam00000/bentopdf
  containerPort: 8080

  service:
    port: 80
    targetPort: 8080
