app:
  name: bentopdf
  image:
    repository: ghcr.io/alam00000/bentopdf
    pullPolicy: IfNotPresent
    tag: 2.8.4@sha256:f54b9ed9c56b767e0098b525468206689b666323c2b500b9686c3cf41cdfa348 # renovate: depName=ghcr.io/alam00000/bentopdf
  containerPort: 8080

  service:
    port: 80
    targetPort: 8080
